# Generated by Django 4.2.1 on 2023-06-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.doctor'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nro_documento',
            field=models.CharField(default=False),
        ),
    ]
